### ISSUE TITLE
keycloak-client throws exception from 1.16.1 and up

### ISSUE THREAD

**Issue by Wegi** [jgrodziski/keycloak-clojure#21]
Hi,

when upgrading to 1.16.1 or higher, instantiating a client results in the following error:

```
Execution error (NoClassDefFoundError) at keycloak.deployment/keycloak-client (deployment.clj:71).
clojure/tools/logging/impl/LoggerFactory
```

The code is taken straight from the documentation and works until, including, 1.16.0.
```
(def kc-client
  (-> (client-conf {:auth-server-url auth-url
                    :realm realm
                    :client-id "admin-cli"})
      (keycloak-client backend-admin-id backend-admin-secret)))
```

**Comment by jgrodziski** [comment]
Yes, I changed recently the way the thin jar is built by adding Keycloak-Clojure's AOT classes along clj files without any other dependencies classes.
How do you declare the keycloak-clojure's dependency? with tools.deps? leiningen?

**Comment by Wegi** [comment]
Hi, thanks for the prompt answer.

We use deps.edn with the following declaration: `keycloak-clojure/keycloak-clojure {:mvn/version "1.16.4"}`

Do you need any extra infos?

**Comment by jgrodziski** [comment]
Thank you that's enough informations, I'll setup a sample project to reproduce and isolate the error. Maybe I messed up the jar building...

**Comment by jgrodziski** [comment]
Hi Alexander,

I've released a new [`1.16.5` version](https://clojars.org/keycloak-clojure/versions/1.16.5) that should fix the issue. I've messed up the Jar building process with AOT while trying to optimise some loading stuff (long story short: just don't, see https://clojureverse.org/t/deploying-aot-compiled-libraries/2545).

**Comment by Wegi** [comment]
Hi Jérémie,

thanks for your swift work. Everything works as expected again. 👍
